// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCUdjEOK24WImSV35mWupcO9w9jXftgaA',
    appId: '1:50575855147:web:d1d1265c5fb7b25697a46e',
    messagingSenderId: '50575855147',
    projectId: 'todo-f475e',
    authDomain: 'todo-f475e.firebaseapp.com',
    storageBucket: 'todo-f475e.appspot.com',
    measurementId: 'G-54WZTRTWRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXTp-WCQyO9iBhQ5aPfAGQs1ym5JLTfkM',
    appId: '1:50575855147:android:6557537988c1632097a46e',
    messagingSenderId: '50575855147',
    projectId: 'todo-f475e',
    storageBucket: 'todo-f475e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDotcyWlGHLvjOI2o_jbFBAtyuGCJlutss',
    appId: '1:50575855147:ios:73f956331ffbd93e97a46e',
    messagingSenderId: '50575855147',
    projectId: 'todo-f475e',
    storageBucket: 'todo-f475e.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDotcyWlGHLvjOI2o_jbFBAtyuGCJlutss',
    appId: '1:50575855147:ios:1bac4a9aefbfdf9e97a46e',
    messagingSenderId: '50575855147',
    projectId: 'todo-f475e',
    storageBucket: 'todo-f475e.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
